app_name: Raw CatFood Calculator
app_subtitle: A simple calculator for your raw catfood needs!
app_download: https://apps.apple.com/us/app/
app_id: 
email: joel@lopezaviles.com
app_icon: /assets/icon.png
favicon: /assets/icon.png

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
